name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Go Modules (if using Go Modules)
      run: |
        go mod tidy
        go mod verify

    - name: build_netstat
      run: GOARCH=amd64 GOOS=linux go build -o watchers/netstat/watchers_netstat watchers/netstat

    - name: build_ps
      run: GOARCH=amd64 GOOS=linux go build -o watchers/ps/watchers_ps watchers/ps

    - name: build_lin_survey
      run: GOARCH=amd64 GOOS=linux go build -o survey/linux/survey_linux survey/linux

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: go-build-artifacts
        path: |
          watchers/netstat/watchers_netstat
          watchers/ps/watchers_ps
          survey/linux/survey_linux
